[package]
name = "asterisk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
asterisk-sys = { version = "0.1.0", path = "../asterisk-sys" }
bitflags = "2.6.0"
log = "0.4.22"
